#ifndef NF_COMMON_H
#define NF_COMMON_H

//// PIN CONFIG
// SCREEN
#define NF_SCREEN_SDA 14
#define NF_SCREEN_SCL 15

// INPUTS
#define NF_BTN0_PIN 10
#define NF_BTN1_PIN 11
#define NF_BTN2_PIN 12

// OUTPUTS
#define NF_SSR0_PIN 2
#define NF_SSR1_PIN 3

#define NF_FAN0_PIN 4
#define NF_FAN1_PIN 5

#define NF_SPKR_PIN 6


#define NF_MENU_BACK_BTN NF_BTN0_PIN
#define NF_MENU_NEXT_BTN NF_BTN1_PIN
#define NF_MENU_SELECT_BTN NF_BTN2_PIN
//#define NF_MENU_BACK_BTN NF_BTN3_PIN

#define NF_BACK_BTN_INDEX 0
#define NF_NEXT_BTN_INDEX 1
#define NF_SELECT_BTN_INDEX 2

// MEMORY RELATED
#define PROFILE_UINT_SIZE 8
#define NUMBER_OF_PROFILES 3


#endif